### PR TITLE
 Update docker to last stable 18.09.4

### PR DESCRIPTION
**Pull request by ambientlight**
### Pull Request Checklist

 Update docker to last stable 18.09.4 so new buildkit can be used to speed up docker builds.

Check/accept these:
- [X] I've updated the version in the Dockerfile
- [X] I've updated the CHANGELOG.md
- [X] I've provided a link or explanation below which describes the changes in the tool itself

https://github.com/ambientlight/bitrise-base/blob/patch-1/CHANGELOG.md

### CODE REVIEW

**Comment by ambientlight** [comment]
still, containerized buildkit doesn't seem to be available even for 18.09.4

**Comment by ghaabor** [comment]
Hey @ambientlight, thanks for the PR! 🚀 We haven't merged it because we need to upgrade docker on the underlying VMs as well and we'll merge the two PRs together but we haven't forgotten about this :)

**Comment by ambientlight** [comment]
@ghaabor: no worries, though I still haven't figured out why exactly docker-in-docker 18.09.4 daemon doesn't not have buildkit support available

**Comment by ghaabor** [comment]
> @ghaabor: no worries, though I still haven't figured out why exactly docker-in-docker 18.09.4 daemon doesn't not have buildkit support available

My guess for now is it's because the host outside has an older docker installed. In this case the installed docker just acts as a docker client inside the container, the actual docker is daemon is running outside, on the VM.

**Pull request merged**
